# This workflow will build, tag, and push the Discord IT Trivia Bot container
# to DockerHub, then deploy the bot to production with Ansible.

---
name: Deploy Discord IT Trivia Bot to production

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - v*
jobs:
  build-container-and-push-with-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Login to DockerHub via Action
        uses: docker/login-action@v1
        with:
          username: chrisjhart
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: DockerHub Setup
        uses: docker/setup-buildx-action@v1
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "chrisjhart/discord-it-trivia:${{ env.TAG }},\
            chrisjhart/discord-it-trivia:latest"
